name: Build DiaCare APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Add Android
        run: npx cap add android

      - name: Sync
        run: npx cap sync android

      - name: Permission
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DiaCare-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
